package entities;
// Generated 15-Jul-2017 18:20:13 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favorite generated by hbm2java
 */
@Entity
@Table(name="favorite"
    ,catalog="pia1"
)
public class Favorite  implements java.io.Serializable {


     private FavoriteId id;
     private User userByIdUser;
     private User userByIdFavoriteUser;

    public Favorite() {
    }

    public Favorite(FavoriteId id, User userByIdUser, User userByIdFavoriteUser) {
       this.id = id;
       this.userByIdUser = userByIdUser;
       this.userByIdFavoriteUser = userByIdFavoriteUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUser", column=@Column(name="idUser", nullable=false) ), 
        @AttributeOverride(name="idFavoriteUser", column=@Column(name="idFavoriteUser", nullable=false) ) } )
    public FavoriteId getId() {
        return this.id;
    }
    
    public void setId(FavoriteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false, insertable=false, updatable=false)
    public User getUserByIdUser() {
        return this.userByIdUser;
    }
    
    public void setUserByIdUser(User userByIdUser) {
        this.userByIdUser = userByIdUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idFavoriteUser", nullable=false, insertable=false, updatable=false)
    public User getUserByIdFavoriteUser() {
        return this.userByIdFavoriteUser;
    }
    
    public void setUserByIdFavoriteUser(User userByIdFavoriteUser) {
        this.userByIdFavoriteUser = userByIdFavoriteUser;
    }




}


