package entities;
// Generated 15-Jul-2017 18:20:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="file"
    ,catalog="pia1"
)
public class File  implements java.io.Serializable {


     private Integer idFile;
     private Presentation presentation;
     private String file;

    public File() {
    }

    public File(Presentation presentation, String file) {
       this.presentation = presentation;
       this.file = file;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFile", unique=true, nullable=false)
    public Integer getIdFile() {
        return this.idFile;
    }
    
    public void setIdFile(Integer idFile) {
        this.idFile = idFile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPres", nullable=false)
    public Presentation getPresentation() {
        return this.presentation;
    }
    
    public void setPresentation(Presentation presentation) {
        this.presentation = presentation;
    }

    
    @Column(name="file", nullable=false, length=200)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


