package entities;
// Generated 15-Jul-2017 18:20:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Picture generated by hbm2java
 */
@Entity
@Table(name="picture"
    ,catalog="pia1"
)
public class Picture  implements java.io.Serializable {


     private Integer idPicture;
     private Session session;
     private String picture;

    public Picture() {
    }

    public Picture(Session session, String picture) {
       this.session = session;
       this.picture = picture;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPicture", unique=true, nullable=false)
    public Integer getIdPicture() {
        return this.idPicture;
    }
    
    public void setIdPicture(Integer idPicture) {
        this.idPicture = idPicture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSession", nullable=false)
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }

    
    @Column(name="picture", nullable=false, length=200)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }




}


