package entities;
// Generated 15-Jul-2017 18:20:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Presentation generated by hbm2java
 */
@Entity
@Table(name="presentation"
    ,catalog="pia1"
)
public class Presentation  implements java.io.Serializable {


     private Integer idPresentation;
     private Conference conference;
     private Session session;
     private String name;
     private String authors;
     private Date start;
     private Set files = new HashSet(0);

    public Presentation() {
    }

	
    public Presentation(Conference conference, Session session, String name, String authors) {
        this.conference = conference;
        this.session = session;
        this.name = name;
        this.authors = authors;
    }
    public Presentation(Conference conference, Session session, String name, String authors, Date start, Set files) {
       this.conference = conference;
       this.session = session;
       this.name = name;
       this.authors = authors;
       this.start = start;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPresentation", unique=true, nullable=false)
    public Integer getIdPresentation() {
        return this.idPresentation;
    }
    
    public void setIdPresentation(Integer idPresentation) {
        this.idPresentation = idPresentation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idConference", nullable=false)
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSession", nullable=false)
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }

    
    @Column(name="name", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="authors", nullable=false, length=300)
    public String getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(String authors) {
        this.authors = authors;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="start", length=8)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="presentation")
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }




}


