package entities;
// Generated 15-Jul-2017 18:20:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name="session"
    ,catalog="pia1"
)
public class Session  implements java.io.Serializable {


     private Integer idSession;
     private Conference conference;
     private String type;
     private String room;
     private Date date;
     private Date starts;
     private Date ends;
     private Set pictures = new HashSet(0);
     private Set presentations = new HashSet(0);

    public Session() {
    }

	
    public Session(Conference conference, String type, String room, Date date) {
        this.conference = conference;
        this.type = type;
        this.room = room;
        this.date = date;
    }
    public Session(Conference conference, String type, String room, Date date, Date starts, Date ends, Set pictures, Set presentations) {
       this.conference = conference;
       this.type = type;
       this.room = room;
       this.date = date;
       this.starts = starts;
       this.ends = ends;
       this.pictures = pictures;
       this.presentations = presentations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSession", unique=true, nullable=false)
    public Integer getIdSession() {
        return this.idSession;
    }
    
    public void setIdSession(Integer idSession) {
        this.idSession = idSession;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idConfFK", nullable=false)
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }

    
    @Column(name="type", nullable=false, length=15)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="room", nullable=false, length=45)
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="starts", length=8)
    public Date getStarts() {
        return this.starts;
    }
    
    public void setStarts(Date starts) {
        this.starts = starts;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ends", length=8)
    public Date getEnds() {
        return this.ends;
    }
    
    public void setEnds(Date ends) {
        this.ends = ends;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="session")
    public Set getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Set pictures) {
        this.pictures = pictures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="session")
    public Set getPresentations() {
        return this.presentations;
    }
    
    public void setPresentations(Set presentations) {
        this.presentations = presentations;
    }




}


